### ISSUE TITLE
[Bug] 世界书无法进行递归匹配

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [dingyi222666/koishi-plugin-chathub#277]
一个 keywords 的文本下面并不能匹配到其他的条目。比如 content “喜欢吃牛排” 并不能匹配到 keywords：牛排

```
- keywords:
      - 喜欢的食物
  content: 你喜欢吃牛排

- keywords:
      - 牛排
  content: 牛排，或称牛扒，是片状的牛肉，是西餐中常见的食物之一。牛排的烹调方法以煎和烤制为主。
```
