### ISSUE TITLE
[Feature] 非官方 API 使用 Deepseek R1 模型时，隐藏 <think> 标签内容

### ISSUE THREAD

**Issue by samnyan** [dingyi222666/koishi-plugin-chathub#369]
现在的`<think></think>`内容太长，在群里发送比较刷屏。

是不是应该增加一个选项隐藏think内容？

支持编辑消息的平台或许可以显示成 `已思考...s`

更新：解决方案见 https://github.com/ChatLunaLab/chatluna/issues/369#issuecomment-2630956572

**Comment by dingyi222666** [comment]
这种标签不是通用标准，ChatLuna 暂时不打算兼容。
但是你可以使用 `postHandler`，要求模型将内容输出在 `output` 标签里，然后手动过滤。

https://github.com/ChatLunaLab/chatluna/blob/20a9b1e43a5302df1bae3b60a76f770210d0dbb2/packages/core/resources/presets/chatgpt.yml#L70

或者:
```yml
format_user_prompt: |-
  # 当前时间
  {time_UTC+8}
  {weekday}

  # 消息发送者
  QQ 号: {sender_id}
  群昵称: "{sender}"

  # 消息内容
  {prompt}

  # 输出规范
  <output> 将回复内容包裹在 xml 标记中。在一行内输出，不在标记后换行。output 标签是绝对不可以省略的！</output>

config:
  postHandler:
    censor: false
    prefix: '<output>'
    postfix: '</output>'
```
