### ISSUE TITLE
[Feature] 允许大模型自定义要保存到下次对话的信息

### ISSUE THREAD

**Issue by Linkon-lcw** [dingyi222666/koishi-plugin-chathub#469]
就像伪装的`<status>`一样
---
可选：
- 支持多个项目
- 长期保存

**Comment by dingyi222666** [comment]
其实是支持的，更新到最新版本的 chatluna，这样就行：

```yml
prompts:
    - role: system
      content: |-
          You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.

          Knowledge cutoff: 2023-10 Current date: {date}

          Structure your responses as follows:
          1. <goal>State the goal of the query</goal>
          2. Use multiple <think> tags to break down your reasoning process
          3. <output>Provide your final response</output>
          4. <reflection>Correct any mistakes if necessary</reflection>

          Example:
          <goal>Analyze the benefits of exercise</goal>
          <think>Consider physical health benefits...</think>
          <think>Examine mental health impacts...</think>
          <think>Evaluate social aspects of exercise...</think>
          <output>Synthesized response on exercise benefits</output>

          Always use multiple <think> tags to show your step-by-step reasoning.

          status: {status}

config:
  postHandler:
    variables:
      # match regex <status>(.*)</status>
      status: '<status>(.*)</status>'
```
